we are running from this directory: /lustre1/work/aurorasg/TNG
 the name of the job is: basic_properties
Th job ID is 3935246
The job was run on these nodes: compute-2-0-19
Number of nodes: 1
We are using 1 cores
We are using 1 cores per node
Total of 1 cores
Linux compute-2-0-19.foreman.hpc.ntnu.no 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
./src/cluster_run.sh: illegal option -- f
./src/cluster_run.sh: line 12: [: -gt: unary operator expected
./data/tng-100-1/cutdata/central_id.txt
Traceback (most recent call last):
  File "./src/cluster_run.py", line 24, in <module>
    safe_tester.test_all(args.tng, test_name, int(args.subhalo), 99)
  File "/lustre1/work/aurorasg/TNG/src/safe_tester.py", line 36, in test_all
    temp_cat = test.mass_vel_photo(tng_run, snapshot, dm_part_mass, i)
  File "/lustre1/work/aurorasg/TNG/src/tng100_test.py", line 56, in mass_vel_photo
    gas = il.pandasformat.dict_to_pandas(il.snapshot.loadSubhalo(base_path, snapshot, i, 'gas', fields["gas"]))
  File "/lustre1/work/aurorasg/TNG/src/illustris_python/pandasformat.py", line 97, in dict_to_pandas
    df = pd.DataFrame(data, dtype=object)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 7356, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 7393, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index
Traceback (most recent call last):
  File "./src/cluster_run.py", line 24, in <module>
    safe_tester.test_all(args.tng, test_name, int(args.subhalo), 99)
  File "/lustre1/work/aurorasg/TNG/src/safe_tester.py", line 36, in test_all
    temp_cat = test.mass_vel_photo(tng_run, snapshot, dm_part_mass, i)
  File "/lustre1/work/aurorasg/TNG/src/tng100_test.py", line 56, in mass_vel_photo
    gas = il.pandasformat.dict_to_pandas(il.snapshot.loadSubhalo(base_path, snapshot, i, 'gas', fields["gas"]))
  File "/lustre1/work/aurorasg/TNG/src/illustris_python/pandasformat.py", line 97, in dict_to_pandas
    df = pd.DataFrame(data, dtype=object)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 348, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 459, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 7356, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/share/apps/software/Core/Anaconda3/2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 7393, in extract_index
    raise ValueError('If using all scalar values, you must pass'
ValueError: If using all scalar values, you must pass an index
slurmstepd: error: *** JOB 3935246 ON compute-2-0-19 CANCELLED AT 2021-02-25T16:19:41 DUE TO TIME LIMIT ***
